#!/bin/bash

cd /home/hadi/btcprice/
price=$(curl eur.rate.sx/1BTC)
echo "# Bitcoin Price in EURO" >README.md
echo "" >>README.md
echo "Bitcoin: ${price}€\n" >>README.md
echo "Date: $(date)" >>README.md
git add .
git commit -m "Update price"
git push -u origin main
